
package cn.demo.gbk.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.gbk.demo.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.SaveCustomerResponse")
    public void saveCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Customer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.demo.gbk.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHasBindingList", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.FindHasBindingList")
    @ResponseWrapper(localName = "findHasBindingListResponse", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.FindHasBindingListResponse")
    public List<Customer> findHasBindingList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.demo.gbk.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<cn.demo.gbk.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotBindingList", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.FindNotBindingList")
    @ResponseWrapper(localName = "findNotBindingListResponse", targetNamespace = "http://service.gbk.demo.cn/", className = "cn.demo.gbk.service.FindNotBindingListResponse")
    public List<Customer> findNotBindingList();

}
